batch_size: 2
ckpt: null
data:
  voxel_size: 0.005
  num_points: 8192
  pc_path: /media/george/Projects/Research/2026-CVPR-BiDexHand/affordance-bidex/data/preprocess_data/pot_data/train/100015/obj_points.npy
  pairs_path: /media/george/Projects/Research/2026-CVPR-BiDexHand/affordance-bidex/data/preprocess_data/pot_data/train/100015/grasp_pairs.npy
exp_name: bimanual_smoke_log
gpu: 0
grad_clip: 10.0
log_every: 1
lr: 0.0005
lr_min: 1.0e-07
max_iter: 30
model:
  type: bimanual_diff
  backbone: sparseconv
  backbone_parameters:
    sparseconv: {}
    sparse_glob_conv: {}
  feature_dim: 256
  joint_num: 22
  use_keypoints: true
  diffusion:
    scheduler_type: DDPMScheduler
    scheduler:
      num_train_timesteps: 1000
      prediction_type: v_prediction
    num_inference_timesteps: 50
  weight:
    diffusion: 1.0
num_workers: 2
save_every: 5
seed: 0
train_split: train
val_every: 1000
val_num: 1
val_split: []

